# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af0956540e1cc86d550aff90ce8b33bb96c0b8991b3e1c2cfc99d3dc36bd7b1631ebf9a64659b44c8b1bdacfa6c1f1f6a9045b7a23bbd1cd4b587f7b1aacb22e

test:
  secret_key_base: 5dfccb177fee49983248245bce06bd69d7796885adbfbc680974dff110e464839da22e991ae0f674846e0af3fcdc6980574f1e7c12dd2299b7cb9dcf2cb9bb34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
